repositories:
- name: k8s-as-helm
  url:  https://ameijer.github.io/k8s-as-helm/
releases:
  - name: redis-secret
    installed: true
    namespace: ot-operator
    chart: k8s-as-helm/secret
    version: 1.0.4
    values:
      - type: Opaque
      - secretData:
          "password": surya
